// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.0--rc1
// source: messages.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserState int32

const (
	UserState_None             UserState = 0
	UserState_EnterProductURL  UserState = 1
	UserState_EnterProductName UserState = 2
	UserState_EnterProductPool UserState = 3
	UserState_EnterMinPrice    UserState = 4
	UserState_EnterMinBonuses  UserState = 5
)

// Enum value maps for UserState.
var (
	UserState_name = map[int32]string{
		0: "None",
		1: "EnterProductURL",
		2: "EnterProductName",
		3: "EnterProductPool",
		4: "EnterMinPrice",
		5: "EnterMinBonuses",
	}
	UserState_value = map[string]int32{
		"None":             0,
		"EnterProductURL":  1,
		"EnterProductName": 2,
		"EnterProductPool": 3,
		"EnterMinPrice":    4,
		"EnterMinBonuses":  5,
	}
)

func (x UserState) Enum() *UserState {
	p := new(UserState)
	*p = x
	return p
}

func (x UserState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserState) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[0].Descriptor()
}

func (UserState) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[0]
}

func (x UserState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserState.Descriptor instead.
func (UserState) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

type ButtonID int32

const (
	ButtonID_Invalid           ButtonID = 0
	ButtonID_AddProduct        ButtonID = 1
	ButtonID_ListOfProducts    ButtonID = 2
	ButtonID_SetMinPrice       ButtonID = 3
	ButtonID_SetMinBonuses     ButtonID = 4
	ButtonID_ChangeProductName ButtonID = 5
	ButtonID_DeleteProduct     ButtonID = 6
	ButtonID_MainMenu          ButtonID = 7
	ButtonID_ChangeMenu        ButtonID = 8
)

// Enum value maps for ButtonID.
var (
	ButtonID_name = map[int32]string{
		0: "Invalid",
		1: "AddProduct",
		2: "ListOfProducts",
		3: "SetMinPrice",
		4: "SetMinBonuses",
		5: "ChangeProductName",
		6: "DeleteProduct",
		7: "MainMenu",
		8: "ChangeMenu",
	}
	ButtonID_value = map[string]int32{
		"Invalid":           0,
		"AddProduct":        1,
		"ListOfProducts":    2,
		"SetMinPrice":       3,
		"SetMinBonuses":     4,
		"ChangeProductName": 5,
		"DeleteProduct":     6,
		"MainMenu":          7,
		"ChangeMenu":        8,
	}
)

func (x ButtonID) Enum() *ButtonID {
	p := new(ButtonID)
	*p = x
	return p
}

func (x ButtonID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ButtonID) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[1].Descriptor()
}

func (ButtonID) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[1]
}

func (x ButtonID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ButtonID.Descriptor instead.
func (ButtonID) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

type ListOfProdcutsData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *ListOfProdcutsData) Reset() {
	*x = ListOfProdcutsData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOfProdcutsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOfProdcutsData) ProtoMessage() {}

func (x *ListOfProdcutsData) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOfProdcutsData.ProtoReflect.Descriptor instead.
func (*ListOfProdcutsData) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ListOfProdcutsData) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type ProdcutData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Lastpage int32 `protobuf:"varint,2,opt,name=lastpage,proto3" json:"lastpage,omitempty"`
}

func (x *ProdcutData) Reset() {
	*x = ProdcutData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProdcutData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProdcutData) ProtoMessage() {}

func (x *ProdcutData) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProdcutData.ProtoReflect.Descriptor instead.
func (*ProdcutData) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ProdcutData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProdcutData) GetLastpage() int32 {
	if x != nil {
		return x.Lastpage
	}
	return 0
}

type ButtonData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   ButtonID `protobuf:"varint,1,opt,name=id,proto3,enum=protobufs.ButtonID" json:"id,omitempty"`
	Data []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ButtonData) Reset() {
	*x = ButtonData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ButtonData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ButtonData) ProtoMessage() {}

func (x *ButtonData) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ButtonData.ProtoReflect.Descriptor instead.
func (*ButtonData) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *ButtonData) GetId() ButtonID {
	if x != nil {
		return x.Id
	}
	return ButtonID_Invalid
}

func (x *ButtonData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_messages_proto protoreflect.FileDescriptor

var file_messages_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x22, 0x28, 0x0a, 0x12, 0x4c,
	0x69, 0x73, 0x74, 0x4f, 0x66, 0x50, 0x72, 0x6f, 0x64, 0x63, 0x75, 0x74, 0x73, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x39, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x64, 0x63, 0x75, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x70, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x70, 0x61, 0x67, 0x65,
	0x22, 0x45, 0x0a, 0x0a, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x23,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2e, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x49, 0x44, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x7e, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x13,
	0x0a, 0x0f, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x55, 0x52,
	0x4c, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x6e, 0x74,
	0x65, 0x72, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x50, 0x6f, 0x6f, 0x6c, 0x10, 0x03, 0x12,
	0x11, 0x0a, 0x0d, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x4d, 0x69, 0x6e, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x10, 0x04, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x4d, 0x69, 0x6e, 0x42, 0x6f,
	0x6e, 0x75, 0x73, 0x65, 0x73, 0x10, 0x05, 0x2a, 0xa7, 0x01, 0x0a, 0x08, 0x42, 0x75, 0x74, 0x74,
	0x6f, 0x6e, 0x49, 0x44, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10,
	0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x10,
	0x01, 0x12, 0x12, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x73, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x4d, 0x69, 0x6e, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x65, 0x74, 0x4d, 0x69, 0x6e,
	0x42, 0x6f, 0x6e, 0x75, 0x73, 0x65, 0x73, 0x10, 0x04, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x10, 0x05,
	0x12, 0x11, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x10, 0x06, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x61, 0x69, 0x6e, 0x4d, 0x65, 0x6e, 0x75, 0x10,
	0x07, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x65, 0x6e, 0x75, 0x10,
	0x08, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData = file_messages_proto_rawDesc
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_proto_rawDescData)
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_messages_proto_goTypes = []any{
	(UserState)(0),             // 0: protobufs.UserState
	(ButtonID)(0),              // 1: protobufs.ButtonID
	(*ListOfProdcutsData)(nil), // 2: protobufs.ListOfProdcutsData
	(*ProdcutData)(nil),        // 3: protobufs.ProdcutData
	(*ButtonData)(nil),         // 4: protobufs.ButtonData
}
var file_messages_proto_depIdxs = []int32{
	1, // 0: protobufs.ButtonData.id:type_name -> protobufs.ButtonID
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messages_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ListOfProdcutsData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ProdcutData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ButtonData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		EnumInfos:         file_messages_proto_enumTypes,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_rawDesc = nil
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
